SchoolMVC/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SchoolMVC.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public virtual List<Product> Products { get; set; }
    }
}

SchoolMVC/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolMVC.Models;

namespace SchoolMVC.Controllers
{
    public class CategoriesController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Categories
        public ActionResult Index(string searchString)
        {
            var Categories = from category in db.Categories
                         select category;

            if (!String.IsNullOrEmpty(searchString))
            {
                Categories = Categories.Where(s => s.Type.Contains(searchString));
            }

            return View(Categories);
        }
        /*public ActionResult Index()
        {

            return View(db.Categories.ToList());
        }*/

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Type")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Type")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolMVC/Views/Categories/Create.cshtml
@model SchoolMVC.Models.Category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchoolMVC/Views/Categories/Delete.cshtml
@model SchoolMVC.Models.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SchoolMVC/Views/Categories/Details.cshtml
@model SchoolMVC.Models.Category

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SchoolMVC/Views/Categories/Edit.cshtml
@model SchoolMVC.Models.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchoolMVC/Views/Categories/Index.cshtml
@model IEnumerable<SchoolMVC.Models.Category>
<style>
    .banner {
        align-items: center;
        color: #fff;
        display: flex;
        flex-direction: column;
        justify-content: center;
        height: 100%;
        overflow: hidden;
        position: relative;
        text-align: center;
        width: 100%;
    }
    .product-display {
        background-color: #fff;
        box-shadow: 0 2px 4px rgba(0,0,0,.25);
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        list-style: none;
        margin: 0;
        padding: 0;
        width: 100%;
    }

    .product-display__visual {
        background-color: #f7f7f7;
        flex: 0 0 auto;
        position: relative;
        text-align: center;
        height: 20rem;
    }

    .product-display__categories {
        background-color: rgba(0,0,0,.6);
        box-shadow: 0 2px 4px rgba(0,0,0,.5);
        border-radius: .3rem;
        bottom: 1rem;
        color: #fff;
        display: inline-block;
        left: 2rem;
        padding: .5rem 1.2rem;
        position: absolute;
    }

    .product-display__info {
        display: flex;
        flex: 1 0 auto;
        flex-direction: column;
        justify-content: space-between;
        padding: 2rem 2rem 3.5rem;
    }
    .product-display__image-link {
        background-size: cover;
        background-position: 50%;
        display: block;
        height: 100%;
        left: 0;
        position: absolute;
        text-align: center;
        top: 0;
        width: 100%;
    }
</style>
@{
    ViewBag.Title = "Index";
}
<div class="col-sm-12">
    <div class="banner">

    <h2>Index</h2>
        
    <form asp-controller="Categories" asp-action="Index">
        @Html.ActionLink("Create New", "Create")


        <p>
            Title: <input type="text" name="SearchString">
            <input type="submit" value="Filter" />
        </p>
    </form>
    </div>
</div>

        
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="product-display">
                        <div class="product-display__visual">
                            <a class="product-display__image-link lazyload is-lazyloaded" href="/bugs/" style="background-image:url('/Content/images/TestImage.jpeg');"><img src="~/Conten/images/TestImage.jpeg"/></a>

                            <div class="product-display__categories">
                                Teamgenoot
                            </div>
                        </div>
                        <div class="product-display__info">
                        @Html.DisplayFor(modelItem => item.Type)
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                            </div>
                    </div>
                </div>

            }
        </div>